# Generated by Django 5.0.4 on 2024-04-20 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directions', '0001_initial'),
        ('students', '0003_student_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='direction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='directions.direction', verbose_name='Направление'),
        ),
    ]
