# Generated by Django 5.0.4 on 2024-04-18 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_group_options'),
        ('mentors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='mentor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor_groups', to='mentors.mentor', verbose_name='Ментор'),
        ),
    ]
