# Generated by Django 5.0.4 on 2024-04-20 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directions', '0001_initial'),
        ('groups', '0003_group_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='direction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='directions.direction', verbose_name='Направление'),
        ),
    ]
