# Generated by Django 5.0.4 on 2024-04-13 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_group_options'),
        ('schedules', '0002_remove_schedule_data_alter_schedule_group_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='groups.group', verbose_name='Группа'),
        ),
    ]
